### ISSUE TITLE
Teensy 3.2 Example sketches

### ISSUE THREAD

**Issue by mjs513** [tum-phoenix/drive_teensy_libuavcan#13]
Do you happen to have example sketches for the Teensy to test with.  I primarily use the Arduino IDE to do this with of course the Teensyduino.
Not quite sure how to set this up to work in an Arduino IDE environment.

**Comment by fabolhak** [comment]
Hello mjs513,
we only work with [platformio](http://platformio.org) as IDE and therefore I can not provide any examples for the Arduino IDE right away. I may have time to set up some example code for Arduino IDE in the next weeks.

In the meanwhile, you can have a look at [our application repository](https://github.com/tum-phoenix/drive_teensy_main) which uses the UAVCAN library for teensy in platformio.

If you want to check it out, you only need to install [platformio](https://platformio.org/platformio-ide), clone the application repo, open the folder where the 'platformio.ini' is located and hit the build button. There is an [example application](https://github.com/tum-phoenix/drive_teensy_main/tree/master/src/teensy_example) we use as a reference.

We tried to make it as simple as possible to develop a UAVCAN application for a teensy. However, in order to achieve this, we use some "glue code":

The UAVCAN code is included as a library in the [platformio.ini](https://github.com/tum-phoenix/drive_teensy_main/blob/master/platformio.ini#L18) file. An additional [python script](https://github.com/tum-phoenix/drive_teensy_main/blob/master/lib/libuavcan/build.py) sets it up correctly. Finally, there is a common [header file](https://github.com/tum-phoenix/drive_teensy_main/blob/master/lib/phoenix_can_shield/phoenix_can_shield.h) which is being used in all our applications holding some common functions.

**Comment by mjs513** [comment]
@fabolhak.  Thanks for the added info.

If you have time to work it into the Arduino IDE it would be great help.  Right now I am working on moving it into the Arduino ide since I never used Platform.io before.  Getting there but getting errors such as:
```
C:\Users\CYBERP~1\AppData\Local\Temp\arduino_build_880129\sketch\uavcan_node_airspeed.ino.cpp.o: In function `uavcan::GlobalDataTypeRegistry::RegistrationResult uavcan::GlobalDataTypeRegistry::registerDataType<uavcan::protocol::NodeStatus_<0> >(uavcan::DataTypeID)':
c:\users\cyberp~1\appdata\local\temp\arduino_build_880129\sketch\uavcan\node/global_data_type_registry.hpp:218: undefined reference to `uavcan::GlobalDataTypeRegistry::remove(uavcan::GlobalDataTypeRegistry::Entry*)'
c:\users\cyberp~1\appdata\local\temp\arduino_build_880129\sketch\uavcan\node/global_data_type_registry.hpp:230: undefined reference to `uavcan::GlobalDataTypeRegistry::remove(uavcan::GlobalDataTypeRegistry::Entry*)'
c:\users\cyberp~1\appdata\local\temp\arduino_build_880129\sketch\uavcan\node/global_data_type_registry.hpp:236: undefined reference to `uavcan::GlobalDataTypeRegistry::registImpl(uavcan::GlobalDataTypeRegistry::Entry*)'

```
Most these undefined references are all centered around DataTypes and GlobalRegistry.  Eventually will work it out.

**Comment by mjs513** [comment]
@fabolhak 
I have been trying to work this in the meantime using the Arduino IDE with Teensyduino.  I put the lib into what I think is the right library format and structure for UAVcan and seems to compile without issue but getting a lot of undefined references  here is one of them (a lot is centered around this) but probably all a related issue:
```
C:\Users\CYBERP~1\AppData\Local\Temp\arduino_build_546198\sketch\teensy_example_uavcan.ino.cpp.o: In function `uavcan::GenericSubscriber<uavcan::protocol::GetDataTypeInfo_, uavcan::protocol::GetDataTypeInfo_::Request_<0>, uavcan::TransferListener>::TransferForwarder::~TransferForwarder()':

C:\Users\CyberPalin\Documents\Arduino\libraries\libuavcan_teensy/uavcan/node/generic_subscriber.hpp:133: undefined reference to `uavcan::TransferListener::~TransferListener()'

```
It's like the linker doesn't get the cpp linkages correct to the .hpp files.  I did post on the Teensy forum but no ideas there.  Was wondering if you have any ideas for me to try out - or do I just have to change all the .hpp files to .h files.

Thanks
Mike

**Comment by mjs513** [comment]
Ok.  Got it resolved.  Had to put everything into a src folder for the library and create a library.properties file.  Have one last problem that I am working on:
```
C:\Users\CYBERP~1\AppData\Local\Temp\arduino_build_966599\sketch\teensy_example_uavcan.ino.cpp.o: In function `std::function<void (uavcan::ReceivedDataStructure<uavcan::protocol::debug::KeyValue_<0> > const&)>::operator()(uavcan::ReceivedDataStructure<uavcan::protocol::debug::KeyValue_<0> > const&) const':

c:\local programs\arduino-1.8.5-142b4\hardware\tools\arm\arm-none-eabi\include\c++\5.4.1/functional:2266: undefined reference to `std::__throw_bad_function_call()'
```

**Comment by mjs513** [comment]
@fabolhak .  Well thanks to KurtE on the Teensy forum got it all worked out.  Did have to add one thing to the main sketch to get it to finally compile and run:
```
namespace std {
  void __throw_bad_alloc()
  {
    Serial.println("Unable to allocate memory");
  }

  void __throw_length_error( char const*e )
  {
    Serial.print("Length Error :");
    Serial.println(e);
  }

  void __throw_bad_function_call()
  {
    Serial.println("Bad function call!");
  }
}
```
The example I was running was the one you posted on the GitHub repository drive-teensy-main, teensy-example.  Still have to figure out what its doing.  the only thing I see is keyDiff: 20170 being printed on one of the Teensies.  I loaded the sketch on both.

Here is what I have so far without further testing:

[libuavcan_teensy.zip](https://github.com/tum-phoenix/drive_teensy_libuavcan/files/2267667/libuavcan_teensy.zip)

It works with the Arduino IDE 1.8.5 and Teensyduino 1.42.  I am running on a Windows 10 laptop.  Have it running on a Teensy 3.5 and a Teensy 3.6.

Thanks
Mike

**Comment by fabolhak** [comment]
Hello Mike,

sorry for my late response. Unfortunately, I'm very busy these days. Also, I'm not very experienced in writing libraries for the Arduino IDE. I'm very happy to hear that you got it working.

I also tried it on my (Linux) machine. However, due to the different use of slashes (Linux = forward slash, Windows = backward slash) it had problems compiling the generated header files from the *.uavcan message files. 

So instead of directly including the generated header files in the git repository, it may be better to provide a script which generates the header files on each platform (like [this one](https://github.com/tum-phoenix/drive_teensy_main/blob/master/lib/libuavcan/build.py)).

However, still very good work :+1: .

Kindest regards,
fabolhak
